routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProduitController;
use App\Http\Controllers\CartController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/fiche-produit/{id}', [ProduitController::class, 'getProduit'])->name('fiche-produit');;
Route::post('/creation/delete-image', [ProduitController::class, 'deleteImage']);
Route::get('/creation/{id?}', [ProduitController::class, 'creation'])->name('fiche-backOffice');
Route::post('/creation/{id?}', [ProduitController::class, 'postCreation'])->name('user.postCreation');
Route::resource('/panier', CartController::class)->only(['index', 'store', 'update', 'destroy']);
Route::post('/suppression', [ProduitController::class, 'suppression']);
Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Image.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    protected $table = 'images';

    protected $guarded = [];

    public function produit()
    { 
        return $this->belongsTo(Image::class); 
    }

}

app/Models/Marque.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Marque extends Model
{
    public function produits() 
    { 
        return $this->hasMany(Produit::class); 
    }
}

app/Models/Produit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Produit extends Model
{
    protected $fillable = ['nom', 'prix', 'marque_id', 'description'];

    public function marque()
    { 
        return $this->belongsTo(Marque::class); 
    }

    public function images() 
    { 
        return $this->hasMany(Image::class); 
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services\ProduitService;
use Cart;

class CartController extends Controller
{
    public function __construct( ProduitService $produitService)
    {
        $this->produitService = $produitService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $content = Cart::getContent();
        $total = Cart::getTotal();

        return view('panier.index', compact('content', 'total'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $produit = $this->produitService->getProduit($request->id);
        
        Cart::add([
            'id' => $produit->id,
            'name' => $produit->nom,
            'price' => $request->input('prix'),
            'quantity' => $request->input('quantite'),
            'attributes' => [],
            'associatedModel' => $produit,
        ]
        );
        return redirect()->back()->with('cart', 'ok');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services\ProduitService;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(ProduitService $produitService)
    {
        $this->middleware('auth');
        $this->produitService = $produitService;
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $produits = $this->produitService->getAllProduits();

        return view('home')->with(
            ['produits' => $produits]
        );
    }
}

app/Http/Controllers/ProduitController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;
use App\Services\ProduitService;
use App\Services\MarqueService;
use App\Models\Image;
use Illuminate\Support\Facades\Storage;



class ProduitController extends Controller
{

    public function __construct( ProduitService $produitService, MarqueService $marqueService)
    {
        $this->produitService = $produitService;
        $this->marqueService = $marqueService;
    }

    public function getProduit($id)
    {
        $produit = $this->produitService->getProduit($id);
    
        return view('fiche-produit')->with(
            ['produit' => $produit]
        );  
    }

    public function creation(Request $request, $id=null)
    {
        $produit = $this->produitService->getProduit($id);
        $marques = $this->marqueService->getAllMarques();

        return view('creation')->with(
            ['marques' => $marques,
            'produit' => $produit
            ]
        );

    }

    public function postCreation(Request $request, $id=null)
    {  

        if($request->marque && isset($request->marque))
        {
            $marque = $this->marqueService->saveMarqueInBdd($request->marque);
            $marque_id = $marque->id;
            $produit = $this->produitService->saveProduitInBdd($id, $request, $marque_id);
        }
        else {
            $produit = $this->produitService->saveProduitInBdd($id, $request, $marque_id = null);
        }

        return redirect()->to('fiche-produit/'.$produit->id);   
    }

    public function deleteImage(Request $request)
    {  
        $produit = $this->produitService->deleteImage($request->idImage);
    }
    
    public function suppression(Request $request) 
    {
        $produit = $this->produitService->deleteProduit($request->input('idProduit'));
    
    }
}

resources/views/creation.blade.php
@extends('layouts.app')
@section('content')
<div id="creation" class="p-4">

	@isset($error)
		<div class="alert alert-primary" role="alert">
			{{$error}}
		</div>
	@endisset
	
	{!! Form::model($produit ?? '', array('route' => array('user.postCreation'), 'files' =>true, 'method' =>'post' )) !!}
	{!! csrf_field()!!}
	

		<div class="col-12 d-flex align-items-around">
			<h1>Informations générales</h1>
			@isset($produit->id)
				<div class="btn btn-danger ml-auto p-2" onclick="deleteProduit({{ $produit->id }})">Supprimer le produit</div>
			@endisset
		</div>
		

      	<div class="row bg-light">
			<div class="col-12">

			@isset($produit->id)
				<input type="hidden" name="id" value = "{{$produit->id}}">
			@endisset

				<div class="form-group">
					<label>Nom</label>
					{!! Form::text('nom', null, 
						[
						'class' => 'form-control',
						'required'
						])
					!!}
				</div>

				<div class="col-4 pl-0">
					<h5>Marque</h5>
					<div id="marque-id"> 
					@if(count($marques) > 0 )
					<label>Sélectionner la marque</label>
						<select class="form-control" name="marque_id">	
							@foreach($marques as $marque)
								@isset($produit->marque->id)
									@if ($marque->id == $produit->marque->id)							
										<option value="{{$marque->id}}" selected>{{$marque->nom}}</option>
									@else
										<option value="{{$marque->id}}">{{$marque->nom}}</option>
									@endif
								@else
									<option value="{{$marque->id}}">{{$marque->nom}}</option>	
								@endisset			
							@endforeach
						</select>	
					@else
						<label>Saisir une marque</label>
						<input required  type='text' class='form-control' id='input_marque' name='marque'>
						@endif	
					</div>
					
					@if(count($marques) > 0 )
						<p class="titre-marque bg-info-marque mt-2">Si la marque n'est pas présente, cliquez <span id="ajout-marque" class="text-primary pointer font-weight-bold">ICI</span> pour la renseigner</p>
					@endif
					<div id="conteneur-input-marque"></div>
				</div>


                <div class="row mt-4 bg-light">
                    <div class="form-group col-sm-12">
                        <label for="exampleTextarea">Description</label>
                        {!! Form::textarea('description', null, 
                            [
                            'rows' => 8,
							'class' => 'form-control',
							'required'
                            ])
                        !!}
                    </div>
                </div>
                
                <div class="col-6 pl-0">
                    <label>Prix</label>
                    {!! Form::text('prix', null, 
                        [
						'class' => 'form-control',
						'required'
                        ])
                    !!}
				</div>

				<h3 class="mt-5">Ajouter des nouvelles images au produit</h3>
				<input
					type="file"
					multiple
					name="files[]"
					label="Déposez vos fichiers ou cliquez ici."
					is="drop-files"
				/>		
				
				<div class="pl-3 border border-info mt-4" >
					@isset($produit->images)
						@if (count($produit->images) > 0)
						<h3 class="mt-5">Images déjà enregistrées en Base donnée <br>-> supprimer en cliquant sur la croix</h3>
						<div class="col-12 d-flex">
							@foreach($produit->images as $image)	
								<div class="col-sm-2" id="imageId{{ $image->id }}">
									<img class="img-form"src="{{$image->image_filename}}" alt="3 suisses"/>
									<span class="bg-danger w-100 d-block text-center pointer" onclick="deleteImage({{ $image->id }})">X</span>							
								</div>
							@endforeach
						</div>		
						@endif	
					@endisset			
				</div>

    </div>

			</div>	

  			<button type="submit" class="btn btn-primary mt-5 send">Enregistrer</button>
      	</div>
		
	{!! Form::close() !!}

</div>
@stop

@push('scripts')
<script>

window.Laravel = 
{!! json_encode(['csrfToken' => csrf_token(),]) !!};
window.token = Laravel.csrfToken;

function deleteImage(id)
{
	$.post('/creation/delete-image', {
		idImage :id,
		_token: token
	})

	.done(function(){
		//Supprimer le conteneur HTML avec l'image
		$( "#idImage"+id ).remove();
		location.reload();
	})
}

$('#ajout-marque').on('click',function(){
	$("#conteneur-input-marque").prepend("<input required  type='text' class='form-control' id='input_marque' name='marque'>");
	$('#marque-id').empty();
	$('.titre-marque').empty();
	$('#input_marque').show();
	
});

function deleteProduit(id)
{
	$.post('/suppression', {
		idProduit :id,
		_token: token
	})

	.done(function(){
		alert("le produit est supprimé");
		location.href = "/"; 
	})

}


</script>

@endpush

resources/views/fiche-produit.blade.php
@extends('layouts.app')
@section('content')



@if(isset($produit))
@include('layouts.file-ariane', ['nomProduit' => $produit->nom])

<a href="{{ route('fiche-backOffice', ['id' => $produit->id]) }}" class="pl-3">
    <button type="button" class="btn btn-warning mb-2">Modifier la fiche produit</button>
</a>

<div id="fiche-produit" class="col-12 d-flex border">
    <div class="col-5 pl-0" id="carousel">
    @isset($produit->images)
    @if (count($produit->images) > 0)
        <div class="master">
            <img src="{{$produit->images->first()->image_filename}}">
        </div>
        <div class="thumbnails">
            @foreach($produit->images as $image)
                <img src="{{$image->image_filename}}" alt="3 suisses">
            @endforeach   
        </div> 
    @else 
        <div class="master">
            <img src="/images/image-icone.png">
        </div>

    @endif	
    @endisset	

    </div>
    <div class="col-7" id="infos-produit">
        <div class="row en-tete">
            <div class="col-9">
                <h1>{{$produit->nom}}</h1>
                <h2 class="mt-5">Marque : {{$produit->marque->nom}}</h2>
            </div>
            <div class="col-3 prix-fiche-produit d-flex align-items-center" style="height: 50px;">
                <span id="prix-barre" class="mr-2">{{$produit->prix}} €</span>
                <p class="m-0">
                {{ str_replace(".", ",", $produit->prix - ($produit->prix * 5)/100)}} €    
                </p>
            </div>     
        </div>

        <div class="row infos-complementaires">
            <div class="col-12 d-flex mt-4 mb-2 justify-content-start">
                <button id="clickDescription" class="btn bg-button-fiche mr-2">Description</button>
                <button id="clickLivraison" class="btn bg-button-fiche mr-2">Livraison</button>
                <button id="clickGaranties" class="btn bg-button-fiche mr-2">Garanties et Paiement</button>
            </div>
            <div class="col-12">
                <div id="info-selected" class="p-2">
                    <div id="description">
                        {{$produit->description}}
                    </div>
                    <div id="livraison" style="display:none;">
                        Tout produit en stock est expédié sous 24h, hors week-ends et jours fériés. Si le produit est en réapprovisionnement, le délai de livraison est indiqué sur la fiche produit.

                        Une fois le colis remis au transporteur choisi par le client, les délais de livraison sont les suivants pour la France
                    </div>
                    <div id="garanties" style="display:none;">
                        Indépendamment de la garantie commerciale, et conformément à la réglementation, LIVELLE s'engage à respecter ses obligations relatives aux garanties attachées aux produits vendus sur son site et dans ses différents catalogues, qui figurent dans les articles extraits du Code de la Consommation et du Code Civil 
                    </div>
                </div>
            </div>

            <form class="form-inline mt-4 w-100 justify-content-between col-12 d-flex" action="{{ route('panier.store')}}" method="POST">
                @csrf
                
                <input type="hidden" id="idProduit" name="id" value="{{ $produit->id }}">
                <input type="hidden" name="prix" value="{{($produit->prix - ($produit->prix * 5)/100) }}">
                <div class="col-2 p-2">
                    <div class="input-group">
                        <span class="input-group-btn">
                        <button type="button" class="quantity-left-minus btn btn-info btn-number"  data-type="minus" data-field="">
                            <span class="glyphicon glyphicon-minus">-</span>
                        </button>
                        </span>
                        <input type="text" id="quantity" name="quantite" class="form-control input-number" value="1" min="1" max="100">
                        <span class="input-group-btn">
                        <button type="button" class="quantity-right-plus btn btn-info btn-number" data-type="plus" data-field="">
                            <span class="glyphicon glyphicon-plus">+</span>
                        </button>
                        </span>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Ajouter au panier</button>
            </form>    
        </div>
    </div>       
</div>
@else  
    @include('layouts.file-ariane')  
    <div class="btn btn-danger mt-5">  
        <p>Ce produit n'existe plus!</p>
        <a href="{{ route('home') }}" class="text-white">Retourner à l'accueil du site </a>
    </div>
@endif

@stop

@push('scripts')
<script>

$(function() {
    
    // Bouton quantité
    var quantitiy=0;
   $('.quantity-right-plus').click(function(e){
        
        // Stop acting like a button
        e.preventDefault();
        // Get the field name
        var quantity = parseInt($('#quantity').val());
        
        // If is not undefined
            
            $('#quantity').val(quantity + 1);

          
            // Increment
        
    });

     $('.quantity-left-minus').click(function(e){
        // Stop acting like a button
        e.preventDefault();
        // Get the field name
        var quantity = parseInt($('#quantity').val());
        
        // If is not undefined
      
            // Increment
            if(quantity>0){
            $('#quantity').val(quantity - 1);
            }
    });

    //make the width of the thumbnails images is dynamic
    var imagesNumber        = $(".thumbnails").children().length,
        marginBetweenImages =  1,
        totalMargins        = marginBetweenImages * (imagesNumber - 1),
        imageWidth          = (100 - totalMargins) / (imagesNumber);
        
    $(".thumbnails img").css({
        marginRight: marginBetweenImages + "%"
    });

    $(".thumbnails img").on("click", function() {
        $(this).addClass("active").siblings().removeClass("active");
        $(".master img").hide().attr("src", $(this).attr("src")).fadeIn(300);
    });

})

// Afficher les infos cliquées
$('#clickDescription').on('click',function(){
    $('#livraison').hide();
    $('#garanties').hide();
    $('#description').show();
});

$('#clickLivraison').on('click',function(){
    $('#description').hide();
    $('#garanties').hide();
    $('#livraison').show();
});

$('#clickGaranties').on('click',function(){
    $('#description').hide();
    $('#livraison').hide();
    $('#garanties').show();
});


</script>

@endpush

resources/views/home.blade.php
@extends('layouts.app')
@section('content')

@include('layouts.file-ariane')

<div>
    <div class="row">

    @if( count($produits) > 0)
    <div class="col-12 cards-container d-flex">
      @foreach($produits as $produit)
        <div class="card col-3 mr-3 p-2">
          <div class="card-image">
              <a href="{{ route('fiche-produit', ['id' => $produit->id]) }}" class="w-100">
                  @if(isset($produit->images->first()->image_filename))
                    <img class="image-home" src="{{$produit->images->first()->image_filename}}" alt="3 suisses">
                  @else
                    <img class="image-home mt-4 mb-3" src="/images/image-icone.png" alt="3 suisses">
                  @endif     
             </a>
          </div>          
          <div class="card-content center-align">
            <p class="font-weight-bold">{{ $produit->nom }}</p>         
          </div>
          <div class="d-flex">
                    <p><strong>{{ number_format($produit->prix, 2, ',', ' ') }} € TTC</strong></p>
                </div>
        </div>
    @endforeach
    </div>
    @else
    <div class="alert alert-warning" role="alert">
        Aucun produit enregistré en BDD !
    </div>
    @endif
    
  </div>
</div>
@stop

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Test Shopinvest</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <!-- include jQuery library -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/styles.css') }}" rel="stylesheet">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
</head>
<body>
    <header id="header" class="row mr-0 ml-0">
        <div class="col-sm-3 align-self-center">
            <a href="" id="logo" >
                <img src="/images/logo3s.svg" alt="logo 3 suisses"/>
            </a>
        </div>
            
        <!-- Authentication Links -->
        @guest
            @if (Route::has('login'))
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('login') }}">Se connecter</a>
                </li>
            @endif

            @if (Route::has('register'))
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('register') }}">Créer un compte</a>
                </li>
            </ul>    
            @endif
        @else
            <div class="col-sm-3 offset-sm-4 mt-3">
                <a href="" id="icon-account" class=""></a>
                <ul class="text-right">
                    <li class="nav-item dropdown list-unstyled">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle p-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }}
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('fiche-backOffice') }}">Création produit</a>    
                            <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();">
                                    Se déconnecter
                                </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                    </li>
                </ul>
            </div>                           
        @endguest
        <div class="col-2 mt-3 text-center">
            <a href="" id="icon-cart"></a>
            @if ($cartCount)
                <span>{{ $cartCount }} article </span> @if($cartCount > 1)s @endif <br> <span> Montant : {{ number_format($cartTotal, 2, ',') }}€ </span>
            @endif
            
        </div>          
    </header>
    @yield('content')
    <script type="module" src="//unpkg.com/@grafikart/drop-files-element"></script>
</body>
@stack('scripts')
</html>

resources/views/layouts/file-ariane.blade.php
<div class="row m-0 menu mt-4 mb-4">
    <div class="col-12 d-flex" id="file-ariane">
        <a href="">Accueil ></a>
        <a href="">Femme ></a>
        <a href="{{ route('home') }}">Tops </a>
        @isset ($nomProduit)
            <p> > {{$nomProduit}}</p>
        @endisset
    </div>
</div>

resources/views/panier/index.blade.php
@extends('app.base')

@section('content')
<div class="container">

  <div class="row">
    <div class="col s12">
      <div class="card">        
        <div class="card-content">
          <div id="wrapper">          
            @if($total)
              <span class="card-title">Mon panier</span>            
              @foreach ($content as $item)
                <hr><br>
                <div class="row">
                  <form action="{{ route('panier.update', $item->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="col m6 s12">{{ $item->name }}</div>
                    <div class="col m3 s12"><strong>{{ number_format($item->quantity * $item->price, 2, ',', ' ') }} €</strong></div>
                    <div class="col m2 s12">
                      <input name="quantity" type="number" style="height: 2rem" min="1" value="{{ $item->quantity }}">
                    </div>
                  </form>
                  <form action="{{ route('panier.destroy', $item->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <div class="col m1 s12"><i class="material-icons deleteItem" style="cursor: pointer">delete</i></div>
                  </form>              
                </div>
              @endforeach
              <hr><br>
              <div class="row" style="background-color: lightgrey">
                <div class="col s6">
                  Total TTC (hors livraison)
                </div>
                <div class="col s6">
                  <strong>{{ number_format($total, 2, ',', ' ') }} €</strong>
                </div>
              </div>
            @else
            <span class="card-title center-align">Le panier est vide</span>
            @endif
          </div>        
          <div id="loader" class="hide">
            <div class="loader"></div>
          </div>
        </div>
        <div id="action" class="card-action">
          <p>
            <a  href="">Continuer mes achats</a>
            @if($total)
              <a href="#">Commander</a>
            @endif
          </p>
        </div>
      </div>
    </div>
  </div>

</div>
@endsection

@section('javascript')
  <script>

    document.addEventListener('DOMContentLoaded', () => {
      const quantities = document.querySelectorAll('input[name="quantity"]');
      quantities.forEach( input => {
        input.addEventListener('input', e => {
          if(e.target.value < 1) {
            e.target.value = 1;
          } else {
            e.target.parentNode.parentNode.submit();
            document.querySelector('#wrapper').classList.add('hide');
            document.querySelector('#action').classList.add('hide');
            document.querySelector('#loader').classList.remove('hide');
          }
        });
      }); 

      const deletes = document.querySelectorAll('.deleteItem');
      deletes.forEach( icon => {
        icon.addEventListener('click', e => {
          e.target.parentNode.parentNode.submit();
          document.querySelector('#wrapper').classList.add('hide');
          document.querySelector('#loader').classList.remove('hide');
        });
      }); 
    });
    
  </script>
@endsection